### ISSUE TITLE
Maker Day feedback

### ISSUE THREAD

**Issue by tracygardner** [raspberrypilearning/rainbow-predictor#2]
https://docs.google.com/document/d/1em836bIhSrdc1cEu-cZHCi0EYGxsknbim_XhCnP8uM4/edit

To be considered when this project is migrated.

**Comment by caitlynraspberrypi** [comment]
All feedback implemented except for the first, about the sense.clear() command. A note was left on the feedback document explaining why this feedback was not actioned.
